# Fastfile

fastlane_version '2.226'

default_platform :ios

platform :ios do
  desc 'Builds project and executes unit tests'
  lane :unit_test do |options|
    scan(
      clean: options[:clean] || false,
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution] || false
    )
  end
end
